### ISSUE TITLE
Software was created on newer version of QGIS and could not be loaded

### ISSUE THREAD

**Issue by ect123** [ubc-library-rc/qgis-walkability#17]
I'm using version 3.22.6-Białowieża (older LTR), and when executing the .qgz project file QGIS gives me an error:

<img width="865" alt="Screen Shot 2023-07-11 at 1 51 15 PM" src="https://github.com/ubc-library-rc/qgis-walkability/assets/14874423/15bb2209-3491-4c67-b739-42275f1ea7cc">

When upgrading to 3.28.8-Firenze I get this message:
` INFO    Project file is older : This project file was saved by QGIS version 3.22.13-Białowieża. When saving this project file, QGIS will update it to version 3.28.8-Firenze, possibly rendering it useless for older versions of QGIS.`

Not sure why that is, but it might be worth considering requiring 3.28.8 LTR as the default software.

**Comment by ect123** [comment]
The project doesn't open. But reading the workshop, it seems like it's blank anyway to start. So I think a solution would be to just not start with a project file at all, open a new empty project, and add the layers that way.

**Comment by lilydemet** [comment]
good point. Instructions have been updated to reflect opening a new project and saving to workshop-data folder!
