### ISSUE TITLE
Avoid using labels for steps

### ISSUE THREAD

**Issue by ect123** [ubc-library-rc/qgis-walkability#18]
There's some interesting styling happening on `/content
/process.md` that has to do with using the class `{: .label .label-step}`.

I would remove those and all of the line breaks (`<br>`) and just use headings. Instead of using an unordered list for steps, use the class for workshops steps:
```
* *1*{: .circle .circle-blue} `.circle-blue`
```

**Comment by lilydemet** [comment]
fixed
